export const ELM_REGISTER = {
    buttonSubmit: "[data-qa='signup-button']",
    buttonSubmitCreateAccount: "[data-qa='create-account']",
    checkboxMr: "#id_gender1",
    fieldRegisterForm: ".signup-form",
    inputEmail: "[data-qa='signup-email']",
    inputName: "[data-qa='signup-name']",
    inputPassword: "[data-qa='password']",
    inputFirstName: "[data-qa='first_name']",
    inputLastName: "[data-qa='last_name']",
    inputCompany: "[data-qa='company']",
    inputAddress: "[data-qa='address']",
    inputAddress2: "[data-qa='address2']",
    inputState: "[data-qa='state']",
    inputCity: "[data-qa='city']",
    inputZipcode: "[data-qa='zipcode']",
    inputMobileNumber: "[data-qa='mobile_number']",
    selectDay: "[data-qa='days']",
    selectMonth: "[data-qa='months']",
    selectYear: "[data-qa='years']",
    selectCountry: "[data-qa='country']",
    labelTitleTxtCenter: "[data-qa='title-txt-center']",
    labelCreateAccount: "b",
    textNewUserSignup: "New User Signup!",
    textEnterAccount: "Enter Account Information",
};